# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
graph-tool=2.96
# It is recommended to install the following from PyPI:
# pip install -r requirements.txt
matplotlib>=3.10.1
networkx>=3.4.2
networkx-temporal>=1.2.1
numpy>1.26.4
pandas>=2.2.3